language: generic

git:
  depth: false

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - sudo apt-get update
  - sudo apt install -y libxml2 libxml2-utils python-lxml

script: ant test

after_script: ant docker-stop
