language: java
git:
  depth: false
jdk: openjdk8

branches:
  only:
    - master
    - develop
    - /^feature.*/

env:
  global:
    - VERSION=${TRAVIS_COMMIT:0:8}
    - BRANCH=$TRAVIS_BRANCH
    - PROJECT_NAME=opensiddur-client
    - INSTANCE_BASE=${PROJECT_NAME}-${BRANCH//\//-}
    - INSTANCE_NAME=${INSTANCE_BASE}-${VERSION}
    - BACKUP_BUCKET_BASE=opensiddur-database-backups
    - ZONE=us-west2-a
    - MACHINE_TYPE=n1-standard-1
    - IMAGE=ubuntu-1804-bionic-v20190617
    - IMAGE_PROJECT=ubuntu-os-cloud
    - BOOT_DISK_SIZE_GB=20
    - EXIST_MEMORY=3072
    - STACK_MEMORY=512
    - SERVICE_ACCOUNT=opensiddur-deploy-1@opensiddur-client.iam.gserviceaccount.com
    - secure: 2s9ydDeMHBfI87szDRo3tl2t8O7O5ILVIv9qcfuuCf4K7xovuavvoVgV0ti81IYz/GcVa/ZlTRN3hkjiO6ZL2gltZLqJvczYBoFFuKHBJujFw0PHedJkwBvyAxMiNx/v2vQUbzzx6cETrL91CenddEGqKnP7Ufpis4zKIz4BP6drmkNiDKdkMs9UctXXfl3+0WZH+2wwpcY2hAUcv/z14qftA8eDDhHcZAHB+Cp+1BQ5ifkknUBS8/5tDOL/FD7J/4uGztA5pO9iU++7hVdMdJpBunFoJ8aVDohM3Bbz7Q0MfnabZj+eUV7RYoyaAJGEfXzCM2AR4RDTKVoBvyDSUfoUb/eVPlDyZVsC2d0w8qtkd5pMLTNc+OMAYLDBw8CxUMQ8ibLxN1+oSi0zORzf/CkZ51UtM1M315y1jm53PW3un3Kqh22Zs8jmVfdIqCTOV/WA6PS7t18CovaoTpoiCvUW7bso1lNaU2g09yUhtnYQuYNpqaL0hrClvktZgiCWDF60GamyyzBGkC3+ObaPbgS3JKPmZWSuuEkopy/IAUcF+svldQhNNeAdp6gG1Yy0PdCE4US2+l0hz+P9O+XEQb7ksIIr7OuVxtowcBCT3wxjy2KgAsDhIc+yUgxMUuMQpsHsM9d6C2PFCr7GH0qBdihH+JlI+eFy7W9SymPqmv0=
    - secure: kGtZTU+RPbrdhf0jdZugpBBi9XcPZViKYLiFvVy7L7b+oa5dVzN8NFMrgg9xTbVOSlYLH75GkLt0bGof4e1zjfo5cbWhSXsEDhuDdduHlOh41LVmR7vO8JQYXfdt+CG+xwfMMfGSBTXirAxDe5tx+etHcOLtcacRB9WE3wqtmm0tcbhh0+MggS06XmGPVl+R201pdBmhXlJHSh/iP/RWfcNoWYFGRaG7zlurpRLgfwKZE0228pmIIA10LYQDQsw1bw86tz6fIJbIOLwhOMobp9fq9T5Ss7QUM56aO865OcUoCQ9jA7zi0sfaNiQIOHWWbFNDfAZzBbS45b7Tm+DBQn88rfABnhVEAG1FNgrFauVmr9CrR832qghfz7I0z0ewjQKsKFQHnECRD/HbBOkxWGyLd0q9ic4L7UFsO2CHuch38VnK2gaDha6UXQJlWqoAUfmLHwu9HoLFLgnYCMtRWwEnww49DZkV/wkn2s/mb2Hl0M9RHyk4LbYV1XvbeVQ9SiVoie6rEiejDqLiCE/vMWNlxohIQOR0+UiNw3aYmAX6kJ/vgv3AZ8tIVY1+KNvtaXvWOAkDUxUs0gy62uZXQg171mbAF8dSCa3Cv5CTIVOFxUZLuJnef/3WTNqtp3MoMu9GTae/Oruf+1go3Jk/BdSfUDxa75EQiEx/wnPR4j8=
    - secure: s+vzUKbiWlGrT4j3HiBIjkcYi5HhnVCyhgikHKOkTng8cPzQAh+eS2f1lJr9ot6C701elJd42KMH9tbMbbv7ge90iVYCOM8lpUbuvaz6UzbOnjPct5mgU934T15E1/EzWd/UWxTDV785lp7ErDxV3vN+JARGgUbuYdVljq5nTh2PgKlpSTtY1iTfmz+m/qI92VVV34kWQ7zRjIyuUce3UjPcNCwC4Kiz3yX74ECaBGCQu99asBsWXpfV13OnnAXyOuNAd9B3k/PKV0bJwjJtOMx2HN3/JqCg9n0VYblSRu40KULKlQ3nNGT2c2U7cQZA4NMwH8/4fHY/63DAb5PbdYXnDcSVKkZcgunfK5YwKwmnZs4nziATHrEFrheVX8MEwfxib3c4sto/sebXV5C9Kq81zzxiB4tkvv8DGIzguzp9xejlWHNMSLPIhSlTfwj0TgC5ZgOmZM8vEqIa2owty7OoUzwulvf8rcVMes7vVEtdJuQcXgCQqOA5kfAtbmyTaF2Ermlf0SW4Rqy1yff3Db4zeSz5OBeTElYPgMIKhsIp3bIRtkJcZGFknEmU7GVRdYRMmWT54LOj2IbLIUoCV1FUrnLsCUhQ5QCIuUcHRcfLFz0qFkN9y8h/tRF18gaqWAr5sd5r+A2D33rBWuPCzF2XHqnlnYtIMfsVTTa/K5o=
    - secure: uFR6muiG1EGRvsSKPwV8iYIbH0HIQ+4bSs3/YbAMgNE/nfQngGucwNa+dosc9EAB3a6jMNlSNHvBqKdaPXunoacG9NmfxSnKlSGDhMfLQqxtI7GWAXHa/yv5qWNJKlj7lYCwGFX/zvGg6tavDxrw6oOOkvvB6QqBsuMoFK72FgcWCepjOdWnBh5zxEb141fK73tUNj8jDN4plU0sWf43s5Cz9wCLwB0kLaZOQ+raaSqCnQ3zXUOcCKKBLSqEvIPtIdvLzZC0f9VrQwF7LjcSfXTrnog3Kmmpi0wyIrPTQ5bdWt6CVRZRZq4bNiylaj8VvjiFJqFtqP0irZ4K08bUaA6IqVuYXlu6fV2TF6XXdbGXzS9ECb5TiodfiWI9Uvz4BdbVfjGhnVVxn76qYYC7VoJVnxLXK/znZeagYkalk5lo8vdjgqwaZjHrWKY7/6GJTKE08uc0uAlm9xoHyHUdUWt9PIQ1VPVLGu5HUypoGuds1WK4Zi5aq6Vn0W+nFtURnlVMWCYLtG+R2SnyHpbjXX68IwukI3wYq8DwRWAHMqSoKaZDbltctfgCnghybL0VNaCEgMD49xWqdkWfuEfpc3qRinOj8AFIhH6tiREC2ICcu/oSBlWfQjTLLjiYhPSCZdM3nKUv9XoOEgploYCVQAcyV9zILNhjC6Vx4nj/blM=

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
    -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  - sudo apt-get update -y
  - sudo apt install -y libxml2 libxml2-utils python3-lxml google-cloud-sdk ant openjdk-8-jdk
  - openssl aes-256-cbc -K $encrypted_3565cb433837_key -iv $encrypted_3565cb433837_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar zxvf credentials.tar.gz
  - gcloud auth activate-service-account --key-file=client-secret.json
  - gcloud config set project ${PROJECT_NAME}
  - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine

script:
  - ant test
  - |
    gcloud compute \
      --project=${PROJECT_NAME} instances create ${INSTANCE_NAME} \
      --zone=${ZONE} \
      --machine-type=${MACHINE_TYPE} \
      --network=default \
      --network-tier=PREMIUM \
      --maintenance-policy=MIGRATE \
      --scopes=https://www.googleapis.com/auth/cloud-platform \
      --tags=http-server,https-server \
      --image=${IMAGE} \
      --image-project=${IMAGE_PROJECT} \
      --boot-disk-size=${BOOT_DISK_SIZE_GB}GB \
      --boot-disk-type=pd-standard \
      --boot-disk-device-name=${INSTANCE_NAME} \
      --service-account=${SERVICE_ACCOUNT} \
      --metadata-from-file startup-script=setup/gcloud-startup-script.sh \
      --metadata ADMIN_PASSWORD=${ADMIN_PASSWORD},EXIST_MEMORY=${EXIST_MEMORY},STACK_MEMORY=${STACK_MEMORY},BRANCH=${BRANCH},DYN_USERNAME=${DYN_USERNAME},DYN_PASSWORD=${DYN_PASSWORD},DYN_EMAIL=${DYN_EMAIL},BACKUP_BUCKET_BASE=${BACKUP_BUCKET_BASE},enable-oslogin=true

after_script:
  - ant docker-stop
